
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://plgvelumspzjzdtmjtlw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsZ3ZlbHVtc3B6anpkdG1qdGx3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3MzU1OTksImV4cCI6MjA2MjMxMTU5OX0.tsE5ofIpFPYPOqhlN8giOunFvshtGgmTgLAtuH1Beq4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
